force-app/main/default/objects/Context__c/Context__c.object-meta.xml
<CustomObject>
    <description>A place to put information about each Apex context we have investigated.</description>
    <label>Context</label>
    <nameField>
        <label>Context Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contexts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Context__c/fields/AggregateQueries__c.field-meta.xml
<CustomField>
    <fullName>AggregateQueries__c</fullName>
    <description>The total number of aggregate queries that can be processed with SOQL query statements.</description>
    <inlineHelpText>The total number of aggregate queries that can be processed with SOQL query statements.</inlineHelpText>
    <label>Aggregate Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if a batch Apex job invoked the executing code, or false if not. In API version 35.0 and earlier, also returns true if a queueable Apex job invoked the code.</description>
    <inlineHelpText>True if a batch Apex job invoked the executing code, or false if not. In API version 35.0 and earlier, also returns true if a queueable Apex job invoked the code.</inlineHelpText>
    <label>Batch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/Callouts__c.field-meta.xml
<CustomField>
    <fullName>Callouts__c</fullName>
    <description>The total number of Web service statements that can be processed.</description>
    <inlineHelpText>The total number of Web service statements that can be processed.</inlineHelpText>
    <label>Callouts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/CpuTime__c.field-meta.xml
<CustomField>
    <fullName>CpuTime__c</fullName>
    <description>The time limit (in milliseconds) of CPU usage in the current transaction.</description>
    <inlineHelpText>The time limit (in milliseconds) of CPU usage in the current transaction.</inlineHelpText>
    <label>Cpu Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/DMLRows__c.field-meta.xml
<CustomField>
    <fullName>DMLRows__c</fullName>
    <description>The total number of records that can be processed with any statement that counts against DML limits, such as DML statements, the database.EmptyRecycleBin method, and other methods.</description>
    <inlineHelpText>The total number of records that can be processed with any statement that counts against DML limits, such as DML statements, the database.EmptyRecycleBin method, and other methods.</inlineHelpText>
    <label>DML Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/DMLStatements__c.field-meta.xml
<CustomField>
    <fullName>DMLStatements__c</fullName>
    <description>The total number of DML statements or the database.EmptyRecycleBin methods that can be called.</description>
    <inlineHelpText>The total number of DML statements or the database.EmptyRecycleBin methods that can be called.</inlineHelpText>
    <label>DML Statements</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/EmailInvocations__c.field-meta.xml
<CustomField>
    <fullName>EmailInvocations__c</fullName>
    <description>The total number of email invocation (such as sendEmail) that can be called.</description>
    <inlineHelpText>The total number of email invocation (such as sendEmail) that can be called.</inlineHelpText>
    <label>Email Invocations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/Future__c.field-meta.xml
<CustomField>
    <fullName>Future__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the currently executing code is invoked by code contained in a method annotated with future; false otherwise.</description>
    <inlineHelpText>True if the currently executing code is invoked by code contained in a method annotated with future; false otherwise.</inlineHelpText>
    <label>Future</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/FutureCalls__c.field-meta.xml
<CustomField>
    <fullName>FutureCalls__c</fullName>
    <description>The total number of methods with the future annotation that can be executed (not necessarily completed).</description>
    <inlineHelpText>The total number of methods with the future annotation that can be executed (not necessarily completed).</inlineHelpText>
    <label>Future Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/HeapSize__c.field-meta.xml
<CustomField>
    <fullName>HeapSize__c</fullName>
    <description>The total amount of memory (in bytes) that can be used for the heap.</description>
    <inlineHelpText>The total amount of memory (in bytes) that can be used for the heap.</inlineHelpText>
    <label>Heap Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/MobilePushApexCalls__c.field-meta.xml
<CustomField>
    <fullName>MobilePushApexCalls__c</fullName>
    <description>The number of Apex calls that have been used by mobile push notifications during the current metering interval.</description>
    <inlineHelpText>The number of Apex calls that have been used by mobile push notifications during the current metering interval.</inlineHelpText>
    <label>Mobile Push Apex Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/Queries__c.field-meta.xml
<CustomField>
    <fullName>Queries__c</fullName>
    <description>The total number of SOQL queries that can be issued.</description>
    <inlineHelpText>The total number of SOQL queries that can be issued.</inlineHelpText>
    <label>Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/QueryLocatorRows__c.field-meta.xml
<CustomField>
    <fullName>QueryLocatorRows__c</fullName>
    <description>The total number of records that can be returned by the Database.getQueryLocator method.</description>
    <inlineHelpText>The total number of records that can be returned by the Database.getQueryLocator method.</inlineHelpText>
    <label>Query Locator Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/QueryRows__c.field-meta.xml
<CustomField>
    <fullName>QueryRows__c</fullName>
    <description>The total number of records that can be returned by issuing SOQL queries.</description>
    <inlineHelpText>The total number of records that can be returned by issuing SOQL queries.</inlineHelpText>
    <label>Query Rows</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/Queueable__c.field-meta.xml
<CustomField>
    <fullName>Queueable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if a queueable Apex job invoked the executing code. Returns false if not, including if a batch Apex job or a future method invoked the code.</description>
    <inlineHelpText>True if a queueable Apex job invoked the executing code. Returns false if not, including if a batch Apex job or a future method invoked the code.</inlineHelpText>
    <label>Queueable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/QueueableJobs__c.field-meta.xml
<CustomField>
    <fullName>QueueableJobs__c</fullName>
    <description>The maximum number of queueable jobs that can be added to the queue per transaction. A queueable job corresponds to a class that implements the Queueable interface.</description>
    <inlineHelpText>The maximum number of queueable jobs that can be added to the queue per transaction. A queueable job corresponds to a class that implements the Queueable interface.</inlineHelpText>
    <label>Queueable Jobs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if the currently executing code is invoked by a scheduled Apex job; false otherwise.</description>
    <inlineHelpText>True if the currently executing code is invoked by a scheduled Apex job; false otherwise.</inlineHelpText>
    <label>Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Context__c/fields/SoslQueries__c.field-meta.xml
<CustomField>
    <fullName>SoslQueries__c</fullName>
    <description>The total number of SOSL queries that can be issued.</description>
    <inlineHelpText>The total number of SOSL queries that can be issued.</inlineHelpText>
    <label>Sosl Queries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sidekick__e/Sidekick__e.object-meta.xml
<CustomObject>
    <description>Simple event used to test the context limits of Apex that handles a platform event.</description>
    <label>Sidekick</label>
    <pluralLabel>Sidekicks</pluralLabel>
</CustomObject>

force-app/main/default/classes/ContextDetective.cls
/**
 * An inquisitive little class hell-bent on exploring various Apex contexts and the related limits of those contexts.
 */
@RestResource(UrlMapping='/context-detective')
global with sharing class ContextDetective implements Schedulable, Database.Batchable<Object> {

	private final String contextDescription;

	public ContextDetective(String contextDescription) {
		this.contextDescription = contextDescription;
	}

	/**
	 * Kick off a bunch of different permutations of how Apex can be invoked so we can log them.
	 */
	public static void investigate(String description) {

		// call the Apex REST endpoint
		Http h = new Http();
		HttpRequest req = new HttpRequest();
		req.setEndpoint(Url.getOrgDomainUrl().toExternalForm() + '/services/apexrest/context-detective');
		req.setMethod('GET');
		req.setHeader('Authorization', 'Bearer ' + UserInfo.getSessionId());
		h.send(req);

		// run a batch
		Database.executeBatch(new ContextDetective('Batchable'));

		// run a queueable
		System.enqueueJob(new ContextDetectiveQueueable('Queueable'));

		// schedule this class
		Datetime nextRun = System.now().addMinutes(1);
		String cron = '0 ' + nextRun.minute() + ' ' + nextRun.hour() + ' ' + nextRun.day() + ' ' + nextRun.month() + ' ? ' + nextRun.year();
		System.schedule('ContextDetective Scheduled', cron, new ContextDetective('Scheduled'));

		// schedule a batch
		System.scheduleBatch(new ContextDetective('ScheduledBatch'), 'ContextDetective ScheduledBatch', 1);

		// call a future
		future();

		// fire a platform event
		EventBus.publish(new Sidekick__e());

		// dump the context we were called from
		dumpContext(description);
	}

	@Future
	public static void future() {
		dumpContext('Future');
	}

	public void execute(SchedulableContext sc) {
		dumpContext('Scheduled');

		// kill the scheduled job
		CronTrigger existingJob = [SELECT Id FROM CronTrigger WHERE CronJobDetail.Name = 'ContextDetective Scheduled' LIMIT 1];
		if(existingJob != null)
			System.abortJob(existingJob.Id);
	}

	public Iterable<Object> start(Database.BatchableContext bc) {
		dumpContext(contextDescription + '.start()');
		return new List<Object>{1, 2, 3};
	}

	public void execute(Database.BatchableContext bc, List<Object> records) {
		dumpContext(contextDescription + '.execute()');

		System.enqueueJob(new ContextDetectiveQueueable('Queueable from inside a Batch'));
	}

	public void finish(Database.BatchableContext bc) {
		dumpContext(contextDescription + '.finish()');
	}

	@HttpGet
	global static void httpGet() {
		dumpContext('Apex REST');
	}

	/**
	 * Write a dump of the current limits to an instance of our Context custom object. Use a descriptive name to describe
	 * the current context you're calling from, something like "Inside Chained Queueable", etc.
	 *
	 * @param contextDescription
	 */
	public static void dumpContext(String contextDescription) {

		// we use the description as a unique identifier so we avoid dupes in the table
		upsert new Context__c(
			Name = contextDescription,
			Batch__c = System.isBatch(),
			Future__c = System.isFuture(),
			Queueable__c = System.isQueueable(),
			Scheduled__c = System.isScheduled(),
			AggregateQueries__c = Limits.getLimitAggregateQueries(),
			Callouts__c = Limits.getLimitCallouts(),
			CpuTime__c = Limits.getLimitCpuTime(),
			DMLRows__c = Limits.getLimitDmlRows(),
			DMLStatements__c = Limits.getLimitDmlStatements(),
			EmailInvocations__c = Limits.getLimitEmailInvocations(),
			FutureCalls__c = Limits.getLimitFutureCalls(),
			HeapSize__c = Limits.getLimitHeapSize(),
			MobilePushApexCalls__c = Limits.getLimitMobilePushApexCalls(),
			Queries__c = Limits.getLimitQueries(),
			QueryLocatorRows__c = Limits.getLimitQueryLocatorRows(),
			QueryRows__c = Limits.getLimitQueryRows(),
			QueueableJobs__c = Limits.getLimitQueueableJobs(),
			SoslQueries__c = Limits.getLimitSoslQueries()
		) Context__c.Name;
	}
}